{% set version = "0.13.0" %}

package:
  name: delocate
  version: {{ version }}

source:
  fn: delocate-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/delocate/delocate-{{ version }}.tar.gz
  sha256: a93e67a9f56ee01a3f7096a042231d4ac37fecac873cd5ea34ea2b4f43a8fa13

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - packaging
    - typing-extensions
    - macholib

test:
  requires:
    - pip
  imports:
    - delocate
  commands:
    - pip check
    - delocate-listdeps -h
    - delocate-wheel -h

about:
  home: https://github.com/matthew-brett/delocate
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Move OSX dynamic libraries into package
  description: |
    Delocate provides macOS utilities to find dynamic libraries imported
    from python extensions, copy needed dynamic libraries to directory
    within package, and update macOS install_names and rpath to cause code
    to load from copies of libraries
  doc_url: https://github.com/matthew-brett/delocate
  dev_url: https://github.com/matthew-brett/delocate

extra:
  recipe-maintainers:
    - jschueller
    - isuruf
