{% set version = "0.10.4" %}

package:
  name: delocate
  version: {{ version }}

source:
  fn: delocate-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/delocate/delocate-{{ version }}.tar.gz
  sha256: eae712f46f23481ac82250b9dc357280b8cd17ac0e57dce08654d5f722793c93

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - wheel
    - six
    - packaging

test:
  imports:
    - delocate
  commands:
    - delocate-listdeps -h
    - delocate-wheel -h

about:
  home: https://github.com/matthew-brett/delocate
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Move OSX dynamic libraries into package

extra:
  recipe-maintainers:
    - jschueller
    - isuruf
